# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7cf3ce08ab451f3256d3b03307a5848b9e96f9427b50d15508e10763d90b01bb0fc94be42d8cca886a4f7ffe8ddbb2054b20014e6443c33df4ad01d67bb6259

test:
  secret_key_base: d1aecd297cc1145a0ad0627f8f0c114b1668e7d4e062880bc0090ef83aa6c78db9d5f78490246a7e993cfcaae25a56edc594a48b8108f3dfe27694cd8d214a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
